### ISSUE TITLE
getnetworkhashps

### ISSUE THREAD

**Issue by jaycee1967** [CallMeJake/BlockCrawler#3]
Nothing wrong with this code, just that I don't have getnetworkhashps as a COMMAND option, so the blockcrawler always shows "Method not found(Error Code: -32601)" when calculating network hashrate. I did try to insert the command wherever I found gethashespersec in the source code of the client (daemon obviously, but just kept getting errors.

Any way of getting around this? I did try moving the getnetworkhashps function from the php, but that made the blockcrawler lose the information to the right.

**Comment by CallMeJake** [comment]
Sorry I've been absent however an if statement as dimecoinco suggested, or simply commenting out the required lines when using a wallet without this feature, is the proper solution for this.

If I'm misunderstanding (I haven't been in this code in a very long time) feel free to contact me.
